FROM node:18-bullseye AS base

FROM python:3.12-slim

# 从 Node.js 镜像复制整个 /usr/local 目录以确保所有依赖都被复制
COPY --from=base /usr/local /usr/local

WORKDIR /app

# 安装 NPM 依赖
COPY package.json package-lock.json ./
RUN npm install

# 安装 Python 依赖
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 复制应用代码
COPY . .

# 暴露端口

EXPOSE 5000

# 环境变量
ENV PYTHONUNBUFFERED=1

# 启动服务
CMD ["python", "-m", "web.app"]